### ISSUE TITLE
Make sure images scale properly

### ISSUE THREAD

**Issue by cjwd** [inuitcss/base.images#6]
Hi,

I was thinking that you should add height:auto to base images so that images keep their aspect ratio when using max-width:100%

**Comment by csshugs** [comment]
Can you give an example please? I didn't ever had the case where this evoked a false aspect ratio.

**Comment by cjwd** [comment]
Sure, I should have done that in the first place.
Well I make WordPress themes and I've been creating my starter theme framework and used http://wptest.io/ to test the basic styles.
There is a test where a user adds a image much bigger than the content container say 1280px and according to the test its not suppose to overflow the container but my theme failed and it did. This was because of inuits' declaration of .gm-style img, img[width], img[height] which I don't have a problem with. So I added a declaration specifically to handle WordPress' images and added max-width:100% but the image did not scale properly. This could be specific to WordPress but I'm not totally sure.

I added an extension to the base image declaration adding height: auto (this is by the way in the Automattic's underscores starter theme) and that fixed the problem.

No height:auto
![no height auto specified](https://cloud.githubusercontent.com/assets/2500771/7784747/cbc146ba-013e-11e5-8175-60e2a8fb2e6b.png)

height:auto
![height auto specified](https://cloud.githubusercontent.com/assets/2500771/7784752/e025a09c-013e-11e5-9a63-d047e863a130.png)

**Comment by csshugs** [comment]
@cjwd 
The Problem is, that you set a `width` and `height` attribute in your HTML. If you drop that, the aspect ratio should be alright without setting `height: auto`. 

I never set any `width` or `height` attributes because of the issue you described above and in my opinion it makes no sense to assign these attributes in responsive websites. There may be cases where you want a specific image size for which, I guess, the declaration

``` scss
.gm-style img, 
img[width], img[height] {
    max-width: none;
}
```

is provided.

The question is: Do you need the `width` and `height` attributes? If you don't, I would suggest to drop them and you wont need any extra CSS. 
If you really do need the attributes, you could create a helper class like:

``` scss
.img-keep-ratio {
    max-width: 100%;
    height: auto;
}
```

...which you could assign to these images.

Either way, I think your issue is an edge case for any inuitcss user and therefore in my opinion, `height: auto` should not be added to the base images module.

---

Thanks for the detailed response, by the way!

**Comment by cjwd** [comment]
i didn't put that in the html. WordPress does that, that's why I said it could be a WordPress specific problem.

Anyway since its WordPress specific, I guess this matter is closed.
